### ISSUE TITLE
Defi App just kept crashing. 

### ISSUE THREAD

**Issue by mrblueSG** [DeFiCh/app#106]
Am on the latest version v.2.1.3.. No matter how i install/un-install, am not able to access the wallet... Can't even force it to do a re-index.. 

![image](https://user-images.githubusercontent.com/75731418/101624796-72f19c00-3a55-11eb-96c8-1478b186f96f.png)

Refer to log files: 
[DFIApp-AppLog.log](https://github.com/DeFiCh/app/files/5665569/DFIApp-AppLog.log)
[DFIApp-BinaryLog.log](https://github.com/DeFiCh/app/files/5665570/DFIApp-BinaryLog.log)

[DFIApp-AppConfig.conf.log](https://github.com/DeFiCh/app/files/5665571/DFIApp-AppConfig.conf.log)
(kindly remove the .log extension as i am unable to upload the .conf file type.. 

Appreciate your prompt action as I am really keen to provide Liquidity to the pools.. Thanks!

**Comment by izzycsy** [comment]
Hi @mrblueSG ,  thanks for your feedback. May I know the OS + version no. you're using? Please give us time to investigate this. Thank you for your understanding.

**Comment by mrblueSG** [comment]
Hi, I am using Windows 10, version 20H2.. I have tried installing and un-installing the app.. No matter how many times I tried, it still kept showing this error.. Can't even load the wallet to do a re-index.

**Comment by izzycsy** [comment]
Hi @mrblueSG , I see, I understand your frustration, please give us some time to investigate this. Thank you.

**Comment by mrblueSG** [comment]
Hi, any update on the following issue?

**Comment by izzycsy** [comment]
Hi @mrblueSG , thanks for following up. The team is still investigating this issue, however we'll be releasing a new update soon, it might address your issue. I'll update the link here once it's ready! Thank you for your patience.

**Comment by izzycsy** [comment]
Hi @mrblueSG , thank you for waiting. Please try the follow steps and let me know the result. 

Step 1: 
Go to Folder: **/Users/username/Library/Application Support/DeFi**

Step 2: Find `anchors` folder

Step 3: Delete `anchors` folder
<img width="619" alt="201217 Delete Anchor Folder" src="https://user-images.githubusercontent.com/65014479/102454955-c2e5e980-4079-11eb-82e5-313a378e1647.png">

Step 4: Start app again

This should resolve your issue.

**Comment by mrblueSG** [comment]
Thanks! It finally worked.. Btw, another question that needed your advice. After I have synchronized against the network, I did an "Import Wallet" as i forgot my mnemonic phrases.. Somehow it doesn't allow the Send/Receiving function. Refer to image. 

![image](https://user-images.githubusercontent.com/75731418/102490936-7b2b8600-40aa-11eb-8c9c-8aa5eee892b3.png)

When I click on DEX, i was able to see the DFI token reflecting correctly.. Any advice? TIA for all your help!

**Comment by izzycsy** [comment]
Hi @mrblueSG , please try the following steps and let me know the result: 
1. **Backup** existing `wallet.dat`, remove from DeFi folder
2. Rename one of the backups to wallet.dat (in my case I’ll rename `1605637015196.dat` to `wallet.dat`)
3. See if your balances are reflected

**Note:**
• Do not delete your backups or DeFi folder
 
<img width="650" alt="201221 Rename wallet dat file" src="https://user-images.githubusercontent.com/65014479/102757945-fe035800-43ac-11eb-95d6-738f9e9c350d.png">

**Comment by champs2k** [comment]
Hi all, i try this already:
 
..Backup existing wallet.dat, remove from DeFi folder
Rename one of the backups to wallet.dat (in my case I’ll rename 1605637015196.dat to wallet.dat)
See if your balances are reflected
Note:
• Do not delete your backups or DeFi folder

--> ...but me App didn't work. 
I see my credit under DEX, but it does not open the various wallets.  what else can I do?  thanks for any help and support

**Comment by mrblueSG** [comment]
Sorry, not able to try out as the Defi APP is acting up AGAIN :( 
Have tried restarting it multiple times (>20) but still wouldn't boot up.. 

![image](https://user-images.githubusercontent.com/75731418/102845523-b29e8780-4448-11eb-999c-f64db212d7f6.png)

**Comment by izzycsy** [comment]
Hi @mrblueSG , please wait for the update to be launch the above should be resolved. You'll have to: 
• create a new wallet 
• yes, when prompted to backup wallet 
• note down the new mnemonic seed phase
• import your backup wallet file

Thank you for your patience.

**Comment by izzycsy** [comment]
@champs2k thanks for your feedback, is it with regards to your screen getting stuck as well? Could you elaborate more on your user flow & attach your app logs? Screenshots / screen recordings would be helpful as well! We need more details in order investigate how to reproduce the issue. 

If it's a new issue, please create a new post in the main page, to avoid mixing up with the current issues that are being faced in this page. Thank you.

**Comment by mrblueSG** [comment]
@izzycsy I just tried downloading the newest version v2.1.4.. Still unable to connect to blockchain. 
Fyi, i have disabled my firewall and anti-virus (as i am not sure if this could be a possible cause) but to no avail. Any other solutions? 

![image](https://user-images.githubusercontent.com/75731418/103044702-7be97e00-45bc-11eb-9ed0-1a8b5f764d13.png)

**Comment by izzycsy** [comment]
Hi @mrblueSG , understood. Could you send your app logs again please? Please give us time to investigate this issue.

**Comment by mrblueSG** [comment]
Thanks @izzycsy , kindly refer to the following log files: 


[BinaryLog_281220.log](https://github.com/DeFiCh/app/files/5747232/BinaryLog_281220.log)
[AppLog_281220.log](https://github.com/DeFiCh/app/files/5747234/AppLog_281220.log)
[AppConfig_281220.conf.txt](https://github.com/DeFiCh/app/files/5747235/AppConfig_281220.conf.txt)
(remove the .txt as can't upload config file as not supported).

**Comment by mrblueSG** [comment]
@izzycsy Downloaded the latest version 2.1.5 and the issue still persist... :( 
Fyi, i deactivated my McAfee firewall and anti-virus for an hour before loading the app to no avail. 

![image](https://user-images.githubusercontent.com/75731418/103530790-05edec80-4ec3-11eb-87b4-2bf46de326cf.png)

**Comment by izzycsy** [comment]
Hi @mrblueSG , could you send your latest logs please? The team will continue to investigate and fix it, thank you for your patience. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103534104-346ec600-4ec9-11eb-8c02-a4a9ae7a5c84.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103534114-38024d00-4ec9-11eb-82bf-fa906bba4db5.png">

**Comment by mrblueSG** [comment]
@izzycsy App doesn't even load so not too sure whether the log files will be of any value.. Here is the files for the team investigation. 

[Logs_040121.zip](https://github.com/DeFiCh/app/files/5764614/Logs_040121.zip)

**Comment by izzycsy** [comment]
Hi @mrblueSG , well noted. I've conveyed your latest update on the issue to the team. Please give us time to investigate. Thank you for your patience.

**Comment by mrblueSG** [comment]
It's finally working in 2.1.6.. Thanks @izzycsy for all your help!
