### ISSUE TITLE
"Error occured" notification

### ISSUE THREAD

**Issue by jung-eto** [DeFiCh/app#496]
Hi Team, I just noticed something:

### Issue Details

- **Current DeFi App Version:**
  - v2.1.17
- **Previous DeFi App Version:**
  - v2.1.16
- **Operating System (OS):**
  - macOS Big Sur 11.2.1

### Actual Behavior

1. Open the app
2. Go to "Settings"
3. Immediately, a Defi-App notification shows up "Error occured"
4. Go To "Display"
5. Change Language from German to English (because I want to make screenshots you can read :))
6. Click on "Save Settings"
7. Immediately, a Defi-App notification shows up "Error occured"
8. The changes are done correctly, I can not face any errors...
9. changing the language back to german shows up the same behavior

### Expected Behavior

1. Open the app
2. Go to "Settings"
3. Go To "Display"
4. Change Language from German to English (because I want to make screenshots you can read :))
5. Click on "Save Settings"
6. No error message at all!

### App log / binary log / app config
[App_Logs.zip](https://github.com/DeFiCh/app/files/5970024/App_Logs.zip)

Thanks for investigating! Have a great day :)

**Comment by izzycsy** [comment]
Hi @jung-eto , thanks for your feedback and logs, please give us time to investigate this.

**Comment by izzycsy** [comment]
Hi @jung-eto , the team is unable to reproduce the issue, do you have a screenshot / recording of your error? Update [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Comment by jung-eto** [comment]
Hi @izzycsy , I have the update to v2.3.0 successfully yesterday but are facing new problems for which I will open a new issue.
I really would like to post my app logs, but the app does not store them in my folder. I doesn´t matter if the app is locked or unlocked, no app logs are produced...

I have made a short video of the behavior "error occured" so that you can see what happens:


https://user-images.githubusercontent.com/78017139/109149566-05a5fb00-7768-11eb-8743-49625bda65e6.MOV

**Comment by izzycsy** [comment]
Hi @jung-eto , thanks for the video, I think it's bec you do not have a wallet yet, can you try to create / restore wallet?

**Comment by jung-eto** [comment]
Hi @izzycsy , I have had a wallet restored from which I wanted to make the app logs. As soon as I remove the backup file from its folder, the wallet rests. It seem as if there is no ne wallet.app created while closing, so the app always wants to start from the backup file. When wallet is restored and running and I remove the backup file, unlocking is impossible. I am not at home and will create a new issue later with screenshots

**Comment by izzycsy** [comment]
Hi @jung-eto , when the app is running you should not touch the wallet.dat file — that includes renaming the files / moving it to another folder. If you want to rename / move the file, close the app and do so. But when you reopen the app, you'll have to re-link the wallet.dat file to the app as the app won't be able to the file you renamed / moved. My suggestion is once a wallet.dat has been linked, and you want to rename / move it, create a new wallet.dat with those changes. Then close the app and restore with your new wallet.dat.

**Comment by jung-eto** [comment]
Hi @izzycsy , I did not touch the wallet.dat file, I just removed the backup file from the computer because I thought it is just necessary to restore the wallet once.
Is there a difference between a wallet.dat file and a backup.dat file (which is created by the app with the backup function) or is a backup.dat just a renamed wallet.dat?
In older app versions I restored my wallet with the backup file and then removed it from my computer and everything worked fine because the app used its wallet.dat to store its state...
I hope you know what I mean...

**Comment by izzycsy** [comment]
Hi @jung-eto , yes I understood what you mean. In v2.3.0, the previous `backup wallet` has been replaced with `wallet.dat` should you do a backup / restore. So in a way `wallet.dat` is the new backup wallet. But as it's always been, your understanding is correct, the app uses wallet.dat to store its state.

**Comment by jung-eto** [comment]
Hi @izzycsy , ok, well noted. I copied my backup in the Library/... directory where wallet.dat is located and did a recovery from there. Everything works fine and I already closed issue #561

**Comment by izzycsy** [comment]
Hi @jung-eto , thanks for closing the issue. So this issue is resolved as well?

**Comment by jung-eto** [comment]
Hi @izzycsy , no, the "error occurred" still persists as in the video.

**Comment by izzycsy** [comment]
Hi @jung-eto , try to close the app, wait for 5mins, reopen the app, and `Restore wallet from backup` by linking your PC to the `wallet.dat` location. 

Mac — Go to Folder: ` /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`

**Comment by jung-eto** [comment]
Hi @izzycsy , I did exactly this yesterday. The app is running and I can generate log files, my funds are all shown in the wallet. As soon as I go to settings the "error occurred " message shows up. I can make changes in the settings an save them, the function is working. It is just the error message that shows up.

**Comment by izzycsy** [comment]
Hi @jung-eto , ok understood, can you resend your app logs please? The team will investigate.

**Comment by jung-eto** [comment]
Hi @izzycsy ,
here are the newest app logs:
[App_logs.zip](https://github.com/DeFiCh/app/files/6054199/App_logs.zip)

**Comment by izzycsy** [comment]
Hi @jung-eto , the team investigated and it results in a Mac auto-start permission issue. You can allow permission using [this guide](https://www.softwarert.com/enable-disable-autorun-apps-mac/#:~:text=Allow%20or%20disallow%20apps%20to%20launch%20automatically%20from%20the%20dock&text=Right%2Dclick%20or%20use%20the,with%20your%20Mac%20system%20startup). With this, I'll be closing this issue, if your issues persists, please provide new screenshot / recordings and your logs please. Thank you.
