### ISSUE TITLE
LM: Insufficient Fund 

### ISSUE THREAD

**Issue by Fabialfonso** [DeFiCh/app#999]
#### Actual behavior:
When adding more fund to the liquidity mining the error message "insufficient funds" pops op. As you can see in the screenshots and also the console this shouldn't be a problem

#### Expected behavior:
Adding LM without problems 

#### How to reproduce it (as minimally and precisely as possible):
Straight forward. going into the app, waiting that everything is synchronised, delinking the wallet, going to the tab LM and selecting ETH. Clicking on MAX for Ethereum, deleting the last number of the amount to prevent 0,0 balance of ETH afterwards (seemed to be a problem some time ago) and selecting the only wallet adress. and then execute! 
 

#### What are your environment parameters?

- DeFi Wallet Version: 2.52.
- Operating System (OS): iOS Big Sur 11.4
- Current free storage capacity: 150 GB

#### Anything else we need to know?

Constant issues in the past with UTXO missing even though there should be enough available. I de-activated the other wallet addresses to solve this issue. The new issue is now insufficient fund. 

<img width="220" alt="Bildschirmfoto 2021-07-21 um 09 57 48" src="https://user-images.githubusercontent.com/78506939/126454756-28494670-5d8b-4185-b85d-3ee32b5dbb3c.png">
<img width="1014" alt="Bildschirmfoto 2021-07-21 um 09 55 19" src="https://user-images.githubusercontent.com/78506939/126454761-805dd2b8-8880-4cc3-906c-e52e0495c41d.png">

**Comment by izzycsy** [comment]
Hi @Fabialfonso , it could be because you've multiple addresses and your utxoDFI is spread out, try transferring 1 DFI to address `dPo6...`, it should resolve the issue. More details here: [Difference between utxoDFI and tokenDFI
#846](https://github.com/DeFiCh/app/discussions/846#discussioncomment-897090)

**Comment by Fabialfonso** [comment]
Hi @izzycsy , I did transferred some DFI to my own address before. Nevertheless I did the same again- as shown in the screenshot. But still get the same error message. And I am aware what the difference between UTXO and normal DFI token is. 
thats why I did the pre step of transferring DFI to myself.

<img width="1013" alt="Bildschirmfoto 2021-07-21 um 17 36 56" src="https://user-images.githubusercontent.com/78506939/126518773-602a8f1a-0457-4abf-b1eb-203750d85376.png">
<img width="1034" alt="Bildschirmfoto 2021-07-21 um 17 40 12" src="https://user-images.githubusercontent.com/78506939/126518788-78b79e99-d794-47c6-8256-e25df1be9807.png">

**Comment by Fabialfonso** [comment]
In the meantime it worked once. But run into the same issue again. Also sending 1 DFI to my address didn't help... Please advice

**Comment by izzycsy** [comment]
Hi @Fabialfonso , I'd suggest that you hold majority of your DFI on one address, so you won't face the error. It's likely that the utxoDFI is spread across your multiple address and hence the error. Perhaps instead of 1 DFI, try 5 DFI, and see if your function works.

**Comment by izzycsy** [comment]
Hi @Fabialfonso , update [v2.6.0](https://github.com/DeFiCh/app/releases/tag/v2.6.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Fabialfonso , update [v2.6.1](https://github.com/DeFiCh/app/releases/tag/v2.6.1) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Fabialfonso , update [v2.6.2](https://github.com/DeFiCh/app/releases/tag/v2.6.2) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Fabialfonso , update [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._
